#!/usr/bin/env bash
#author      :Tomas Skalicky <skalicky.tomas@gmail.com>
#===============================================================================

#-------------------------------------------------------------------------------

java_major_version=${1:?}

#-------------------------------------------------------------------------------

configure_java_apt_sources() {
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    local file_contents
    set +e
    read -r -d '' file_contents <<- EOF
	deb       http://ppa.launchpad.net/webupd8team/java/ubuntu   ${current_ubuntu_distribution_name:?}   main
	deb-src   http://ppa.launchpad.net/webupd8team/java/ubuntu   ${current_ubuntu_distribution_name:?}   main
	EOF
    set -e
    set_file_contents \
                      /etc/apt/sources.list.d/java.list \
                      "$file_contents"
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    aptkey_adv EEA14886
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
}

#-------------------------------------------------------------------------------

install_java() {
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    local -r java_major_version=${1:?}
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    local -r filepath=/etc/profile.d/java_environment.sh
    set +e
    read -r -d '' file_contents <<- EOF
	export JAVA_HOME=/usr/lib/jvm/java-$java_major_version-oracle
	java_bin=\$JAVA_HOME/bin
	if [ "\$PATH" != *"\$java_bin"* ]; then
	    export PATH=\$java_bin:\$PATH
	fi
	EOF
    set -e
    set_file_contents \
                      "$filepath" \
                      "$file_contents"
    # For some reason `set +e' does not have any effect direct in
    # reload_profile function. The exit mode needs to be turned off because of
    # SDKMAN.
    set +e
    reload_profile
    set -e
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    echo oracle-java"$java_major_version"-installer shared/accepted-oracle-license-v1-1 select true \
        | debconf-set-selections
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    aptget_update
    aptget_install oracle-java"$java_major_version"-installer
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    local -r jvm_home=/usr/lib/jvm
    for symlink_name in "$jvm_home"/jdk-"$java_major_version"-oracle-amd64 \
                        "$jvm_home"/default-java; do
        create_or_update_symbolic_link \
                                       "$jvm_home"/java-"$java_major_version"-oracle \
                                       "$symlink_name"
    done
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
}

#-------------------------------------------------------------------------------

uninstall_openjdk() {
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    local -r java_major_version=${1:?}
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    aptget_purge "openjdk-${java_major_version}-*"
}

#-------------------------------------------------------------------------------

main() {
    local -r java_major_version=${1:?}
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    configure_java_apt_sources
    install_java "$java_major_version"
    uninstall_openjdk "$java_major_version"
}

#-------------------------------------------------------------------------------

main "$java_major_version"

