#!/usr/bin/env bash
#author      :Tomas Skalicky <skalicky.tomas@gmail.com>
#===============================================================================

# Based on
# https://deb.nodesource.com/setup_7.x

#-------------------------------------------------------------------------------

configure_node_apt_sources() {
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    local -r node_major_version=10
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    local file_contents
    set +e
    read -r -d '' file_contents <<- EOF
	deb       https://deb.nodesource.com/node_${node_major_version}.x   ${current_ubuntu_distribution_name:?}   main
	deb-src   https://deb.nodesource.com/node_${node_major_version}.x   ${current_ubuntu_distribution_name:?}   main
	EOF
    set -e
    set_file_contents \
                      /etc/apt/sources.list.d/node.list \
                      "$file_contents"
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    wget --quiet https://deb.nodesource.com/gpgkey/nodesource.gpg.key --output-document=- \
        | apt-key add -
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
}

#-------------------------------------------------------------------------------

install_node() {
    aptget_update
    # The nodejs package contains the nodejs binary as well as npm.
    aptget_install nodejs
}

#-------------------------------------------------------------------------------

useful_npm_packages_to_install=(
    npm
    tldr              # Provides a simplified man pages with practical examples
)

install_useful_npm_packages() {
    npm install --global "${useful_npm_packages_to_install[@]}"
}

#-------------------------------------------------------------------------------

main() {
    configure_node_apt_sources
    install_node
    install_useful_npm_packages
}

#-------------------------------------------------------------------------------

main

