#!/usr/bin/env bash
#author      :Tomas Skalicky <skalicky.tomas@gmail.com>
#===============================================================================

#-------------------------------------------------------------------------------

node_specific_debian_packages_to_install=(
    nodejs
    npm
)

#-------------------------------------------------------------------------------

install_node_specific_debian_packages() {
    aptget_install "${node_specific_debian_packages_to_install[@]}"
}

#-------------------------------------------------------------------------------

useful_npm_packages_to_install=(
    # FIXME needed?   npm
    tldr              # Provides a simplified man pages with practical examples
)

install_useful_npm_packages() {
    npm install --global "${useful_npm_packages_to_install[@]}"
}

#-------------------------------------------------------------------------------

main() {
    aptget_update
    install_node_specific_debian_packages
    install_useful_npm_packages
}

#-------------------------------------------------------------------------------

main
