#!/usr/bin/env bash
#author      :Tomas Skalicky <skalicky.tomas@gmail.com>
#===============================================================================

#-------------------------------------------------------------------------------

upgrade_python_packages() {
    print_info 'Python packages are being updated:'
    pip3 list --outdated --format=freeze \
        | grep --invert-match '^\-e' \
        | cut --delimiter='=' --fields=1 \
        | xargs --max-args=1 pip3 install --upgrade
}

#-------------------------------------------------------------------------------

main() {
    upgrade_python_packages
}

#-------------------------------------------------------------------------------

main

