#!/usr/bin/env bash
#author      :Tomas Skalicky <skalicky.tomas@gmail.com>
#===============================================================================

#-------------------------------------------------------------------------------

configure_rvm_auto_update() {
    local -r config_file_path=${user_home:?}/.rvmrc
    local -r auto_update_flag_name=rvm_autoupdate_flag
    local -r auto_update_flag_value=2
    if grep "$auto_update_flag_name" "$config_file_path" >/dev/null; then
        sed \
            --in-place \
            --regexp-extended \
            "s;^($auto_update_flag_name)=(.*)$;\1=$auto_update_flag_value;" \
            "$config_file_path"
    else
        echo "$auto_update_flag_name=2" >> "$config_file_path"
    fi
}

##
# It does not make sense to specify a version of ruby which should be installed
# and use (even as default) because the next execution of the script on
# get.rvm.io will install a preconfigured version.
##
configure_ruby() {
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # Follows a installation manual documented on https://rvm.io/rvm/install
    sudo --user="${username:?}" gpg --keyserver hkp://pool.sks-keyservers.net \
        --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
    curl \
         --silent \
         --show-error \
         --location \
         https://get.rvm.io \
    \
    | sudo --user="${username:?}" bash -s stable --ruby
    set +u
    # shellcheck disable=SC1090
    source "${user_home:?}/.rvm/scripts/rvm"
    set -u
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    set +u
    # shellcheck disable=SC1090
    source "${user_home:?}"/.profile
    set -u
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    gem install bundler
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # Due to an error message:
    # "/home/tomas/.rvm/scripts/functions/support: line 182:
    # _system_name: unbound variable"
    set +u
    rvm cleanup all
    set -u
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
}

#-------------------------------------------------------------------------------

main() {
    configure_rvm_auto_update
    configure_ruby
}

#-------------------------------------------------------------------------------

main

